### ISSUE TITLE
Missing properties in wix-window module declaration

### ISSUE THREAD

**Issue by agankarin** [wix-incubator/corvid-types#2]
The following properties are missing in `wix-window` module declaration:

- lightbox

- multilingual

- rendering

**Comment by moshfeu** [comment]
rendering is in #9

**Comment by chaimk** [comment]
@agankarin Is there something that's supposed to happen with this? What is the status?

**Comment by agankarin** [comment]
The issue has been resolved in `corvid-types@1.1.103`
